import type { EventItem } from "@/types";

export const events: EventItem[] = [
  {
    id: 1,
    title: "Tech Conference 2024",
    image: "/images/event1.png",
    slug: "tech-conference-2024",
    location: "San Francisco, CA",
    date: "2024-09-15",
    time: "10:00 AM",
  },
  {
    id: 2,
    title: "AI & ML Summit",
    image: "/images/event2.png",
    slug: "ai-ml-summit",
    location: "New York, NY",
    date: "2024-10-20",
    time: "9:00 AM",
  },
  {
    id: 3,
    title: "Web Development Workshop",
    image: "/images/event3.png",
    slug: "web-development-workshop",
    location: "Los Angeles, CA",
    date: "2024-11-05",
    time: "1:00 PM",
  },
  {
    id: 4,
    title: "Cloud Computing Expo",
    image: "/images/event4.png",
    slug: "cloud-computing-expo",
    location: "Seattle, WA",
    date: "2024-12-10",
    time: "11:00 AM",
  },
  {
    id: 5,
    title: "Cybersecurity Forum",
    image: "/images/event5.png",
    slug: "cybersecurity-forum",
    location: "Chicago, IL",
    date: "2025-01-15",
    time: "2:00 PM",
  },
  {
    id: 6,
    title: "Blockchain & Cryptocurrency Conference",
    image: "/images/event6.png",
    slug: "blockchain-cryptocurrency-conference",
    location: "Miami, FL",
    date: "2025-02-20",
    time: "10:30 AM",
  },
];
